title: Blog do Mundo Tecnológico
email: f132.contato@fatec.sp.gov.br
description: >- # this means to ignore newlines until "baseurl:"
  Um projeto de parceria com a Fatec e Rádio Notícias de Tatuí que traz entrevistas com os principais 
  temas de tecnologia, inovação e transformação digital.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog-tech.github.io" # the base hostname & protocol for your site, e.g. http://example.com

github:
  username: FatecTatuiEstagio

# Links Externos
fatec:
  site: "https://www.fatectatui.edu.br/site4/index.php"
  instagram: "https://www.instagram.com/fatectatui/"
  facebook: "https://www.facebook.com/fatectatui/"

cps:
  site: "https://www.cps.sp.gov.br/"

radio:
  site: "https://www.radionoticias.com.br/"

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Sass configuration
sass:
  style: compressed
  sass_dir: _sass

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .vscode/
  - .git/
  - .github/
  - README.md
  - LICENSE
  - package.json
  - package-lock.json
  - tailwind.config.js
  - assets/audio/
  - scripts/
  - docs/
